### ISSUE TITLE
RDAP /entities Wildcard Behavior

### ISSUE THREAD

**Issue by BourgeoisBear** [RIPE-NCC/whois#1599]
Given a wildcard query as described in:

`https://datatracker.ietf.org/doc/html/rfc9082#section-3.2.3`

for a query of the pattern:

`https://rdap.db.ripe.net/entities?fn=DIGITALOCEAN*`

there is only one result:

`EH3832-RIPE`

but the same query without the wildcard:

`https://rdap.db.ripe.net/entities?fn=DIGITALOCEAN`

returns a larger result:

```
DI2361-RIPE
DI2362-RIPE
EH3832-RIPE
ORG-DOI2-RIPE
PT7353-RIPE
```

I would expect the wildcard to return the larger result.  As-is, RIPE's RDAP behavior is the opposite of ARIN's.  The result is the same whether the asterisk is URL-encoded or not.  I chose the non-encoded version since that is how the RFC specified the query.

**Comment by eshryane** [comment]
Hi @BourgeoisBear thanks for your report, we will look into it

**Comment by MiguelAHM** [comment]
Hi @BourgeoisBear 
We just merged the fix https://github.com/RIPE-NCC/whois/pull/1614
There is a casing issue with the query to Elasticsearch when wildcard is used.
Thanks for reporting

**Comment by BourgeoisBear** [comment]
still having the same issue.

this yields results:

`https://rdap.db.ripe.net/entities?fn=hostinger`

this 404s:

`https://rdap.db.ripe.net/entities?fn=hostinger*`

**Comment by BourgeoisBear** [comment]
Also, is there a way to clone/rsync/bittorrent the RIPE RDAP database?  I just need a way to get abuse contacts so I can report unauthorized access attempts.  Ordinary whois output is non-uniform, and there are often query limits per given time period.

**Comment by shryane** [comment]
Hi @BourgeoisBear the recommended way to mirror the RIPE database is using NRTMv4 : 
https://docs.db.ripe.net/RIPE-Database-Mirror/Near-Real-Time-Mirroring-v4/

You can use IRRd for example:
https://github.com/irrdnet/irrd/blob/main/docs/users/mirroring.rst

Or download the DB dump or object split files directly (updated every night) and parse that yourself (RPSL format):
https://ftp.ripe.net/ripe/dbase/

The RIRs are discussing bulk download of RDAP data, but there is no implementation yet.

**Comment by eshryane** [comment]
Hi @BourgeoisBear we have now released Whois 1.115 which fixes this issue:
https://github.com/RIPE-NCC/whois/releases/tag/930e4aba

Now when I query for 
```
https://rdap.db.ripe.net/entities?fn=DIGITALOCEAN*
```

I get 5 top-level entities in the response:
```
DI2361-RIPE
DI2362-RIPE
EH3832-RIPE
ORG-DOI2-RIPE
PT7353-RIPE
```
